/**
 * Priority levels for personalized actions
 */
export type ActionPriority = 'low' | 'medium' | 'high' | 'critical'

/**
 * Categories for actions aligned with Fearvana life areas
 */
export type ActionCategory =
  | 'mindset'
  | 'relationships'
  | 'wealth'
  | 'fitness'
  | 'health'
  | 'career'
  | 'peace'
  | 'sacred-edge'
  | 'general'

/**
 * Types of actions that can be generated
 */
export type ActionType =
  | 'daily-practice'
  | 'challenge'
  | 'reflection'
  | 'experiment'
  | 'habit'
  | 'breakthrough'
  | 'integration'

/**
 * Represents a personalized action generated by the AI coach
 */
export interface PersonalizedAction {
  /** Unique identifier for the action */
  id: string
  /** Short, actionable title */
  title: string
  /** Detailed description of what to do */
  description: string
  /** Type of action */
  type: ActionType
  /** Estimated time to complete in minutes */
  estimatedTime: number
  /** Life area category this action relates to */
  category: ActionCategory
  /** Priority level */
  priority: ActionPriority
  /** AI reasoning for why this action was recommended */
  reasoning: string
  /** Optional: Related Sacred Edge theme */
  sacredEdgeTheme?: string
  /** Optional: Spiral Dynamics level this action targets */
  spiralLevel?: string
  /** Optional: Expected outcome or benefit */
  expectedOutcome?: string
  /** Optional: Difficulty rating from 1-10 */
  difficulty?: number
}

/**
 * Represents the current action context passed to coaching advice
 */
export interface CurrentAction {
  /** Unique identifier for the action */
  id: string
  /** Action title */
  title: string
  /** Action description */
  description: string
  /** Type of action */
  type?: ActionType
  /** Life area category */
  category?: ActionCategory
  /** Current progress percentage (0-100) */
  progress?: number
  /** Whether the action is completed */
  completed?: boolean
  /** User notes about the action */
  notes?: string
  /** When the action was started */
  startedAt?: string
  /** When the action was completed */
  completedAt?: string
}

import { uiLogger } from './logger'

interface OpenAIConfig {
  apiKey: string
}

class OpenAIService {
  private config: OpenAIConfig | null = null

  constructor() {
    this.loadConfig()
  }

  private loadConfig(): void {
    if (typeof window !== 'undefined') {
      const settings = localStorage.getItem('lifelevels-settings')
      if (settings) {
        try {
          const parsed = JSON.parse(settings)
          if (parsed.openaiApiKey) {
            this.config = { apiKey: parsed.openaiApiKey }
          }
        } catch (error) {
          uiLogger.error('Failed to load OpenAI config', { source: 'openai-service' }, error)
        }
      }
    }
  }

  isConfigured(): boolean {
    return this.config !== null && this.config.apiKey.length > 0
  }

  async generatePersonalizedAction(context: string): Promise<PersonalizedAction> {
    if (!this.isConfigured()) {
      throw new Error('OpenAI API key not configured')
    }

    try {
      const response = await fetch('/api/ai-coach', {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'x-openai-key': this.config!.apiKey
        },
        body: JSON.stringify({ context })
      })

      if (!response.ok) {
        throw new Error(`API request failed: ${response.statusText}`)
      }

      const data = await response.json()
      return data.action as PersonalizedAction
    } catch (error) {
      uiLogger.error('Failed to generate personalized action', { source: 'openai-service' }, error)
      throw error
    }
  }

  async getCoachingAdvice(
    context: string,
    currentAction?: CurrentAction,
    userMessage?: string
  ): Promise<string> {
    if (!this.isConfigured()) {
      throw new Error('OpenAI API key not configured')
    }

    try {
      const response = await fetch('/api/ai-coach', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-openai-key': this.config!.apiKey
        },
        body: JSON.stringify({
          context,
          currentAction,
          userMessage
        })
      })

      if (!response.ok) {
        throw new Error(`API request failed: ${response.statusText}`)
      }

      const data = await response.json()
      return data.response
    } catch (error) {
      uiLogger.error('Failed to get coaching advice', { source: 'openai-service' }, error)
      throw error
    }
  }

  updateConfig(apiKey: string): void {
    this.config = { apiKey }
  }
}

export const openaiService = new OpenAIService()
