// Spiral Dynamics Developmental Levels
export const SPIRAL_DYNAMICS_LEVELS = {
  beige: {
    name: 'Beige (Instinctive)',
    color: '#F5F5DC',
    description: 'Survival: Basic needs, food, water, safety',
    mentality: 'Automatic, reflexive',
    population: '<0.01%',
    theme: 'Stay alive',
    keywords: ['survival', 'instinct', 'basic needs', 'automatic'],
    challenges: ['Physical survival', 'Meeting basic needs'],
    growth_edge: 'Safety and tribal belonging',
  },
  purple: {
    name: 'Purple (Magical/Animistic)',
    color: '#800080',
    description: 'Tribal, Animistic: Ritual, safety in group, magical thinking',
    mentality: 'Animistic, safety via traditions',
    population: '<0.1%',
    theme: 'Keep the spirits happy. Stay safe',
    keywords: ['tribal', 'ritual', 'tradition', 'magical thinking'],
    challenges: ['Group safety', 'Maintaining traditions'],
    growth_edge: 'Personal power and assertiveness',
  },
  red: {
    name: 'Red (Impulsive/Egocentric)',
    color: '#FF0000',
    description: 'Power-driven: Dominance, assertiveness, "might makes right"',
    mentality: 'Egocentric',
    population: '~20% of population, ~5% of influence',
    theme: 'Be powerful, don\'t get controlled',
    keywords: ['power', 'dominance', 'assertiveness', 'ego'],
    challenges: ['Gaining power', 'Avoiding control'],
    growth_edge: 'Order, rules, and higher purpose',
  },
  blue: {
    name: 'Blue (Rules/Order)',
    color: '#0000FF',
    description: 'Authoritarian Order: Religion, structure, right vs wrong',
    mentality: 'Absolutist',
    population: '~40% of population',
    theme: 'Live by the rules for reward later',
    keywords: ['order', 'rules', 'authority', 'right/wrong'],
    challenges: ['Following rules', 'Maintaining order'],
    growth_edge: 'Achievement and strategic thinking',
  },
  orange: {
    name: 'Orange (Achiever)',
    color: '#FFA500',
    description: 'Success-Oriented: Achievement, rationality, capitalism',
    mentality: 'Strategic, scientific',
    population: '~30% of population',
    theme: 'Strive, succeed, win',
    keywords: ['achievement', 'success', 'strategy', 'competition'],
    challenges: ['Achieving goals', 'Winning competition'],
    growth_edge: 'Community and multiple perspectives',
  },
  green: {
    name: 'Green (Sensitive)',
    color: '#008000',
    description: 'Relativistic, Pluralistic: Community, equality, feelings matter',
    mentality: 'Egalitarian, post-modern',
    population: '~15% of population',
    theme: 'All perspectives are valid. Connect and care',
    keywords: ['community', 'equality', 'feelings', 'pluralism'],
    challenges: ['Building consensus', 'Honoring all perspectives'],
    growth_edge: 'Systems thinking and integration',
  },
  yellow: {
    name: 'Yellow (Integral)',
    color: '#FFFF00',
    description: 'Systemic Thinker: Sees all levels as necessary',
    mentality: 'Flex-flow, adaptive, meta-awareness',
    population: '<5% of population',
    theme: 'Live fully, manage complexity, build systems',
    keywords: ['systems', 'integration', 'complexity', 'meta-awareness'],
    challenges: ['Managing complexity', 'Integrating perspectives'],
    growth_edge: 'Holistic consciousness',
  },
  turquoise: {
    name: 'Turquoise (Holistic)',
    color: '#40E0D0',
    description: 'Holistic, Unity-Consciousness: Global empathy, spiritual integration',
    mentality: 'Collective individualism',
    population: '<0.1% of population',
    theme: 'We are all one system',
    keywords: ['unity', 'holistic', 'global', 'spiritual'],
    challenges: ['Global integration', 'Unity consciousness'],
    growth_edge: 'Transpersonal awareness',
  },
  coral: {
    name: 'Coral & Beyond (Speculative)',
    color: '#FF7F50',
    description: 'Unitive/Transpersonal: Not well-formed yet',
    mentality: 'Fully awakened consciousness',
    population: '<0.01% of population',
    theme: 'Fully awakened consciousness',
    keywords: ['unitive', 'transpersonal', 'awakened', 'cosmic'],
    challenges: ['Cosmic consciousness', 'Universal integration'],
    growth_edge: 'Unknown territories',
  },
} as const

// Level-specific coaching insights
export const SPIRAL_COACHING_INSIGHTS = {
  red: {
    motivators: ['Power', 'Respect', 'Immediate results', 'Competition'],
    communication_style: 'Direct, assertive, results-focused',
    growth_strategies: [
      'Set clear, achievable power goals',
      'Use competition as motivation',
      'Focus on immediate wins',
      'Respect their need for autonomy',
    ],
    blind_spots: ['Long-term planning', 'Others\' needs', 'Rules and structure'],
    next_level_preparation: 'Introduce structure and rules as tools for greater power',
  },
  blue: {
    motivators: ['Order', 'Purpose', 'Duty', 'Righteousness'],
    communication_style: 'Structured, respectful of authority, purpose-driven',
    growth_strategies: [
      'Align goals with higher purpose',
      'Create structured plans and routines',
      'Emphasize duty and responsibility',
      'Provide clear guidelines and expectations',
    ],
    blind_spots: ['Flexibility', 'Individual differences', 'Innovation'],
    next_level_preparation: 'Introduce strategic thinking and achievement metrics',
  },
  orange: {
    motivators: ['Achievement', 'Success', 'Efficiency', 'Recognition'],
    communication_style: 'Results-oriented, data-driven, competitive',
    growth_strategies: [
      'Set measurable achievement goals',
      'Use data and metrics for motivation',
      'Create competitive challenges',
      'Focus on efficiency and optimization',
    ],
    blind_spots: ['Relationships', 'Meaning beyond success', 'Sustainability'],
    next_level_preparation: 'Introduce community impact and multiple perspectives',
  },
  green: {
    motivators: ['Community', 'Equality', 'Authenticity', 'Harmony'],
    communication_style: 'Collaborative, empathetic, consensus-seeking',
    growth_strategies: [
      'Connect goals to community benefit',
      'Emphasize collaboration and sharing',
      'Honor feelings and relationships',
      'Create inclusive environments',
    ],
    blind_spots: ['Hierarchy', 'Efficiency', 'Difficult decisions'],
    next_level_preparation: 'Introduce systems thinking and healthy hierarchies',
  },
  yellow: {
    motivators: ['Understanding', 'Integration', 'Complexity', 'Flow'],
    communication_style: 'Adaptive, systemic, contextual',
    growth_strategies: [
      'Present complex, systemic challenges',
      'Allow for flexible, adaptive approaches',
      'Integrate multiple perspectives',
      'Focus on natural flow and emergence',
    ],
    blind_spots: ['Impatience with lower levels', 'Over-complexity'],
    next_level_preparation: 'Develop global and holistic awareness',
  },
  turquoise: {
    motivators: ['Unity', 'Global harmony', 'Spiritual integration', 'Wholeness'],
    communication_style: 'Holistic, intuitive, globally aware',
    growth_strategies: [
      'Connect to global and cosmic purposes',
      'Integrate spiritual and material dimensions',
      'Work with natural rhythms and cycles',
      'Focus on collective evolution',
    ],
    blind_spots: ['Practical implementation', 'Individual needs'],
    next_level_preparation: 'Explore transpersonal dimensions',
  },
} as const
